### PR TITLE
Update housing top part and documentation

### PR DESCRIPTION
**Pull request by SebastianSchildt**
The new version contains holes for HDMI and OTG-USB connection, enabling
easier debugging without needing to remove the hardware from the
housing

### CODE REVIEW

**Comment by SebastianSchildt** [comment]
screenshot

**Review by wenwenchenbosch — COMMENTED** [review]
The pdf file is empty for me:
image

**Comment by SebastianSchildt** [comment]
You need to use a PDF viewer supporting 3D models

**Comment by SebastianSchildt** [comment]
Adobe Reader should be able

**Comment by SebastianSchildt** [comment]
@anntexx  you have Adobe PDF reader to check?

**Comment by wenwenchenbosch** [comment]
I check the pdf using adobe, it works. But as @anntexx suggested, some documentation/readme will be nice, because even using adobe, it is also necessary to active the 3d view feature:
```
To enable 3D content permanently:
	
Go to Edit > Preferences > 3D & Multimedia and then select the Enable playing 3D content checkbox.
```

no linux native pdf view found. Only figure it out using [playonlinux](https://www.playonlinux.com/de/) to install a old buggy adobe to view the pdf also on linux.

**Comment by SebastianSchildt** [comment]
Added  Readme, mentioning Adobe Reader requirement

**Review by eriksven — APPROVED** [review]
Approving this PR. However, I am not able to review the details of the STL file. In addition, I would propose to mention that one needs enable the 3D features even for the Acrobat Reader.

**Pull request merged**
